name: Continuous Integration

on:
  pull_request:
    branches:
      - master  # Or whatever your default branch is named

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Add any other dependencies your scripts/tests require

      - name: Run scripts
        run: python tests/test_all.py  # Assuming test_all.py is where you put your check_script function
